### ISSUE TITLE
CEP8 for Windows: Certificate issue

### ISSUE THREAD

**Issue by ArchAndNull** [Adobe-CEP/CEP-Resources#161]
We're experiencing problems with CEP for Adobe CC 2018 for Windows (Adobe Photoshop Version: 19.0 20170929.r.165 2017/09/29: 1138933  x64). It seems that CEP can't recognize certificate for *.cloudfront.net. When I try to load cloudfront, error appears:

Page failed to load.
The certificate for this server is invalid. You might be connecting to a server which could put your confidential information at risk.
URL: https://d5mzcjgfvy5f.cloudfront.net/frontend/adobeaddin/3.0.1_4584/styles.css?time=1516364154000&version=3.0.1
Error: UNKNOWN (-214)

But when I open the same link in Chrome, certificate shows up as secure and valid thru 11/21/2018. And the latest Photoshop 2018 for Mac opens this link perfectly, so it seems that current CEP 8 for Windows has problems with certificate recognition. Do you have any workaround on this issue?

**Comment by noamraby-ssky** [comment]
We had similar issues with "self signed certificate" error. 
It was solved by adding environment variable:
`NODE_TLS_REJECT_UNAUTHORIZED=0`
But I recommend doing that only as last result.

**Comment by UltimateBrent** [comment]
@noamraby-ssky I'm also having this issue. How did you set the environmental variable?

**Comment by noamraby-ssky** [comment]
@UltimateBrent, I changed manually on local machine (not by code). On windows, search for 'env' on windows menu and the relevant dialogue box should appear.

**Comment by akibnavidkhan** [comment]
We have fixed the issue in CEP and fix should be available in next photoshop release

**Comment by UltimateBrent** [comment]
Just leaving this here in case someone else has this problem and can't wait on the next release. I just set up a localhost proxy for my cloudfront requests with http-proxy.

Here's the gist: https://gist.github.com/UltimateBrent/c6f0ef209343f79e3f46a2695f2401cb

**Comment by ArchAndNull** [comment]
@akibnavidkhan and when this release will be available? There were some updates of PHSP, but this issue is still not fixed

**Comment by desygn** [comment]
Will the next release for Premiere also include this fix?

**Comment by bbb999** [comment]
That is the plan.

**Comment by desygn** [comment]
Great! Any idea on when that might be?

**Comment by bbb999** [comment]
Yes, but we can't discuss the release dates of unannounced products.
