### ISSUE TITLE
node.js error - cep_node.require(...) is not a function

### ISSUE THREAD

**Issue by GradySain** [Adobe-CEP/CEP-Resources#435]
I'm building an extension for After Effects. I have a node.js server running as main.js. I've followed the guide here: https://medium.com/adobetech/how-to-build-a-node-js-server-in-a-panel-ba1d63ea67e2

I've made sure these lines are added to manifest.xml:
```
<Parameter>--enable-nodejs</Parameter>
<Parameter>--mixed-context</Parameter>
```
and this:
```
<Geometry>
	<Size>
		<Height>600</Height>
		<Width>600</Width>
	</Size>
</Geometry>
```
This line - in localServer.html - is throwing an error:
`var localServer = cep_node.require(__dirname + '/server/main.js')();`
error:
`Uncaught TypeError: cep_node.require(...) is not a function`

yet my node.js code still runs - seemingly only the first time and from a fresh start of After Effects. Any help greatly appreciated, I'm trying to understand how to fix this bug.

**Comment by ErinFinnegan** [comment]
Did you check [the node version for compatibility](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef)?

There are several [mixed-context mentions in closed issues](https://github.com/Adobe-CEP/CEP-Resources/issues?q=is%3Aissue+mixed-context)... maybe one of those solutions could help?

**Comment by GradySain** [comment]
I upgraded to node v 16.14.2. Still getting the error...

And I def have the --mixed-context parameter enabled:

```
<Resources>
	<MainPath>./client/localServer.html</MainPath>
	<CEFCommandLine>
		<Parameter>--enable-nodejs</Parameter>
		<Parameter>--mixed-context</Parameter>
		<Parameter>--allow-file-access</Parameter>
                <Parameter>--allow-file-access-from-files</Parameter>
	</CEFCommandLine>
</Resources>
```

My node script is writing files to the file system via 'fs' and the ADM-ZIP library, and that works. Which is weird, right? But only the first time I run the extension...

**Comment by saulpalv** [comment]
on cep 11 just `require` works, `cep_node.require` works in cep 9

**Comment by GradySain** [comment]
I get the error

`Uncaught TypeError: require(...) is not a function`

with CEP 11.0.0

**Comment by Inventsable** [comment]
I always put the following at the top of my HTML before any other JS:

```html
    <script>
        window.require = require || cep_node.require;
    </script>
```

Should fix this for Node compatibility regardless of CEP version.

**Comment by GradySain** [comment]
thanks for your help guys but I am still getting an error. here's my HTML:

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<script>
		window.require = require || cep_node.require;
	    /* This script uses cep_node to start the Node.js server located at '/server/main.js' */
	    var localServer = cep_node.require(__dirname + '/server/main.js')();
	</script>
	<title>Import Example App</title>
</head>
<body>
</body>

<script>
	console.log('hello from localServer.html')
</script>
</html>
```

trying with `cep_node.require` or `require` both give me the error...

**Comment by Govind-gupta75** [comment]
Can you share the sample extension so we can debug it? Also, which version of After effects are you using?

**Comment by GradySain** [comment]
I will have to minimize and clean up my code before I could share- as it is pretty bulky / messy and for a planned commercial project. 

I'm using AE v 22.0.0 (Build 111). 

I am basically building off of this guide: https://github.com/Adobe-CEP/Getting-Started-guides

**Comment by Govind-gupta75** [comment]
Can you have a look into [sample](https://github.com/Adobe-CEP/Samples/tree/master/RSSReader)? It is using different node modules to implement its functionality.

**Comment by GradySain** [comment]
hmmm, do you think I'd run into issues trying that script with After Effects (it says Photoshop compatibility)? I wonder if it might make more sense to try this one [](https://github.com/Adobe-CEP/Samples/tree/master/AfterEffectsPanel) and add a simple node server that does nothing but print to the console...

**Comment by Govind-gupta75** [comment]
Yes, you can try [above](https://github.com/Adobe-CEP/Samples/tree/master/AfterEffectsPanel) sample and try to add simple node server.

**Comment by Govind-gupta75** [comment]
@GradySain Were you able to resolve the error with help of above sample?
